### ISSUE TITLE
Gazebo shuts down

### ISSUE THREAD

**Issue by ckowall** [neka-nat/ros-drcsim#1]
When I attempt to run the simulation, the following error occurs:

libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  30
  Current serial number in output stream:  31
process[atlas_robot_state_publisher-3]: started with pid [84]
gzserver: /usr/include/boost/thread/pthread/recursive_mutex.hpp:101: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
process[multisense_sl_robot_state_publisher-4]: started with pid [130]
[gazebo-2] process has died [pid 82, exit code 255, cmd /opt/ros/indigo/share/drcsim_gazebo/scripts/run_gazebo atlas.world -q __name:=gazebo __log:=/home/developer/.ros/log/35fbd916-f9c9-11e7-ae31-0242ac110002/gazebo-2.log].
log file: /home/developer/.ros/log/35fbd916-f9c9-11e7-ae31-0242ac110002/gazebo-2*.log
process[tf2_buffer_server-5]: started with pid [169]
process[multisense_sl/stereo_proc-6]: started with pid [203]
libdc1394 error: Failed to initialize libdc1394
process[multisense_sl_joint_states_relay-7]: started with pid [255]
process[multisense_sl_laser_scan_relay-8]: started with pid [679]
process[multisense_sl_left_image_raw_relay-9]: started with pid [760]
process[multisense_sl_left_camera_info_relay-10]: started with pid [785]
process[multisense_sl_right_image_raw_relay-11]: started with pid [810]
process[multisense_sl_right_camera_info_relay-12]: started with pid [835]
process[multisense_sl/camera/stereo_proc_simulation_relay-13]: started with pid [860]
libdc1394 error: Failed to initialize libdc1394

**Comment by neka-nat** [comment]
I guess you use nvidia graphic card.
Please try to build image using nvidia-docker branch.

```
git checkout nvidia-docker
docker build -t ros_drcsim:1.0 .
nvidia-docker run -ti --privileged --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device=/dev/dri:/dev/dri ros_drcsim:1.0
```

When the container's shell starts up, execute the following command.

```
roslaunch drcsim_gazebo atlas.launch
```

**Comment by ckowall** [comment]
Ah!  My mistake.  Thanks so much for your quick response and great docker!
