### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ckowall** [neka-nat/ros-drcsim#2]
Using the nvidia branch I get the following error:
(tflearn_env) correy@correy-G752VY:~/Desktop/Robots/Atlas$ sudo nvidia-docker run -ti --privileged --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device=/dev/dri:/dev/dri ros_drcsim:1.0
docker: Error response from daemon: create nvidia_driver_384.111: error looking up volume plugin nvidia-docker: plugin "nvidia-docker" not found.
See 'docker run --help'.

Which seems strange because it tells me to see 'docker run --help' rather than nvidia-docker. 

However the following command actually starts a container and changes the prompt to container@developer:
 sudo (tflearn_env) correy@correy-G752VY:~/Desktop/Robots/Atlas$ sudo docker run -ti --privileged --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device=/dev/dri:/dev/dri ros_drcsim:1.0

Do I need to start an appropriate daemon? If so how do I find out which needs to be started?

**Comment by neka-nat** [comment]
I do not know the cause, but I found the following issues.

https://github.com/NVIDIA/nvidia-docker/issues/437
https://medium.com/@SnowGushiGit/how-to-solve-the-nvidia-docker-problem-error-looking-up-volume-plugin-nvidia-docker-plugin-not-6d148c7c9ceb

Can you try some?
